global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'category-service'
    static_configs:
      - targets: ['localhost:8081']
